#!/bin/bash

rm -rf .dist

compass compile

COMMIT_HASH=$(git rev-parse HEAD)

mkdir -p .dist/spse-po

rsync -av css js images html .dist/spse-po
cp LICENSE index.php README.md template* .dist/spse-po

cd .dist/
rm ../spse-po-$COMMIT_HASH.zip
zip -r ../spse-po-$COMMIT_HASH.zip spse-po/
cd ../ && rm -rf .dist

echo
echo
echo "Building done: spse-po-$COMMIT_HASH.zip created.."